[build]
command = "pnpm --filter web build"
publish = "apps/web/.next"

[build.environment]
NODE_VERSION = "22"
NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
from = "https://luibrandtile.netlify.app/*"
to = "https://luibrandtile.com/:splat"
status = 301
force = true
