// This file is generated by apps/web/scripts/generate-portfolio.mjs.
// Do not edit by hand. Add images to public/portfolio and run the generator.

export type GeneratedPortfolioImage = {
  readonly id: string;
  readonly src: string;
  readonly title: string;
  readonly width: number;
  readonly height: number;
  readonly orientation: "landscape" | "portrait";
};

export const generatedPortfolioImages = [
  {
    "id": "20251114-154302",
    "src": "/portfolio/20251114_154302.jpg",
    "title": "Tile Project Photo",
    "width": 4000,
    "height": 3000,
    "orientation": "landscape"
  },
  {
    "id": "20251201-125707",
    "src": "/portfolio/20251201_125707.jpg",
    "title": "Tile Project Photo",
    "width": 4000,
    "height": 3000,
    "orientation": "landscape"
  },
  {
    "id": "20251217-172615",
    "src": "/portfolio/20251217_172615.jpg",
    "title": "Tile Project Photo",
    "width": 4000,
    "height": 3000,
    "orientation": "landscape"
  },
  {
    "id": "20260204-114751",
    "src": "/portfolio/20260204_114751.jpg",
    "title": "Tile Project Photo",
    "width": 1655,
    "height": 3547,
    "orientation": "portrait"
  },
  {
    "id": "20260204-114801",
    "src": "/portfolio/20260204_114801.jpg",
    "title": "Tile Project Photo",
    "width": 4000,
    "height": 3000,
    "orientation": "landscape"
  },
  {
    "id": "20260219-115805",
    "src": "/portfolio/20260219_115805.jpg",
    "title": "Tile Project Photo",
    "width": 4000,
    "height": 3000,
    "orientation": "landscape"
  },
  {
    "id": "arched-shower-niche-bench-detail",
    "src": "/portfolio/arched-shower-niche-bench-detail.jpeg",
    "title": "Arched Shower Niche Bench Detail",
    "width": 1200,
    "height": 1600,
    "orientation": "portrait"
  },
  {
    "id": "arched-stone-shower-tile",
    "src": "/portfolio/arched-stone-shower-tile.jpeg",
    "title": "Arched Stone Shower Tile",
    "width": 1200,
    "height": 1600,
    "orientation": "portrait"
  },
  {
    "id": "diagonal-entry-tile-before",
    "src": "/portfolio/diagonal-entry-tile-before.jpeg",
    "title": "Diagonal Entry Tile Before",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "fireplace-marble-tile-surround",
    "src": "/portfolio/fireplace-marble-tile-surround.jpeg",
    "title": "Fireplace Marble Tile Surround",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "gray-shower-tile-bench-niche",
    "src": "/portfolio/gray-shower-tile-bench-niche.jpeg",
    "title": "Gray Shower Tile Bench Niche",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "june-2026-dark-stone-kitchen-floor-island-detail",
    "src": "/portfolio/june-2026/dark-stone-kitchen-floor-island-detail.jpg",
    "title": "Dark Stone Kitchen Floor Island Detail",
    "width": 4000,
    "height": 3000,
    "orientation": "landscape"
  },
  {
    "id": "june-2026-dark-stone-kitchen-floor-overview",
    "src": "/portfolio/june-2026/dark-stone-kitchen-floor-overview.jpg",
    "title": "Dark Stone Kitchen Floor Overview",
    "width": 3000,
    "height": 4000,
    "orientation": "portrait"
  },
  {
    "id": "june-2026-dark-stone-kitchen-floor-window-view",
    "src": "/portfolio/june-2026/dark-stone-kitchen-floor-window-view.jpg",
    "title": "Dark Stone Kitchen Floor Window View",
    "width": 3000,
    "height": 4000,
    "orientation": "portrait"
  },
  {
    "id": "june-2026-hex-marble-kitchen-backsplash-range",
    "src": "/portfolio/june-2026/hex-marble-kitchen-backsplash-range.jpg",
    "title": "Hex Marble Kitchen Backsplash Range",
    "width": 4000,
    "height": 3000,
    "orientation": "landscape"
  },
  {
    "id": "june-2026-light-bathroom-floor-long-view",
    "src": "/portfolio/june-2026/light-bathroom-floor-long-view.jpg",
    "title": "Light Bathroom Floor Long View",
    "width": 3000,
    "height": 4000,
    "orientation": "portrait"
  },
  {
    "id": "june-2026-light-bathroom-floor-vanity-view",
    "src": "/portfolio/june-2026/light-bathroom-floor-vanity-view.jpg",
    "title": "Light Bathroom Floor Vanity View",
    "width": 4000,
    "height": 3000,
    "orientation": "landscape"
  },
  {
    "id": "june-2026-marble-bathroom-floor-freestanding-tub",
    "src": "/portfolio/june-2026/marble-bathroom-floor-freestanding-tub.jpg",
    "title": "Marble Bathroom Floor Freestanding Tub",
    "width": 3000,
    "height": 4000,
    "orientation": "portrait"
  },
  {
    "id": "marble-look-entry-tile-angle",
    "src": "/portfolio/marble-look-entry-tile-angle.jpeg",
    "title": "Marble Look Entry Tile Angle",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "marble-look-foyer-tile",
    "src": "/portfolio/marble-look-foyer-tile.jpeg",
    "title": "Marble Look Foyer Tile",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "open-plan-wood-look-tile-floor",
    "src": "/portfolio/open-plan-wood-look-tile-floor.jpeg",
    "title": "Open Plan Wood Look Tile Floor",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "patterned-kitchen-backsplash-detail",
    "src": "/portfolio/patterned-kitchen-backsplash-detail.jpeg",
    "title": "Patterned Kitchen Backsplash Detail",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "patterned-kitchen-backsplash-wide",
    "src": "/portfolio/patterned-kitchen-backsplash-wide.jpeg",
    "title": "Patterned Kitchen Backsplash Wide",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  }
] as const satisfies readonly GeneratedPortfolioImage[];
